---
# Grafana server defaults

grafana_package: grafana
grafana_service_name: grafana-server
grafana_port: 3000
grafana_repo_enabled: true
grafana_repo_baseurl: https://rpm.grafana.com
grafana_admin_user: admin
grafana_admin_password: "{{ lookup('ansible.builtin.env', 'GRAFANA_ADMIN_PASSWORD') }}"
