---
# RedHat family (Rocky/AlmaLinux/CentOS) Slurm variables

slurm_packages:
  - munge
  - munge-libs
  - slurm-ohpc
  - slurm-perlapi-ohpc
  - slurm-contribs-ohpc

slurm_service_name: slurmd
munge_service_name: munge
