---
# Default umask for user privacy
user_umask: "0077"

# Default initial password for newly created users
hpc_default_user_password: "{{ lookup('ansible.builtin.env', 'HPC_DEFAULT_USER_PASSWORD') }}"

# Home directory permissions
home_dir_mode: "0700"

# SSH settings used by create/delete helper scripts
storage_ssh_user: hpcadmin
storage_ssh_key: /home/hpcadmin/.ssh/id_ed25519
