---
ldap_admin_uid: 20000
ldap_admin_gid: 20000
ldap_admin_home: "/home/{{ admin_user }}"
ldap_admin_shell: /bin/bash
ldap_admin_password: "{{ lookup('ansible.builtin.env', 'HPC_DEFAULT_USER_PASSWORD') }}"
ldap_admin_ssh_public_keys: >-
  {{
    (lookup('ansible.builtin.env', 'HPC_ADMIN_SSH_PUBLIC_KEYS') | default('', true)).split('\n')
    | map('trim')
    | reject('equalto', '')
    | list
  }}
ldap_local_uri: ldap://127.0.0.1
sudo_rule_name: hpc-admins
