---
nfs_server_enabled: false

nfs_server_packages:
  - nfs-utils
  - rpcbind
  - quota

nfs_server_rpcbind_service: rpcbind
nfs_server_service: nfs-server
nfs_server_exports_dir: /etc/exports.d
nfs_server_exports_file: /etc/exports.d/hpc.exports
nfs_server_show_exports: true

nfs_exports: []
# Example:
# nfs_exports:
#   - path: /home
#     clients: "*"
#     options: "rw,sync,no_root_squash,no_subtree_check"

quota_enabled: false
nfs_home: /home
