all:
  vars:
    ansible_user: hpcadmin 
    ansible_become: true

  children:
    head:
      hosts:
        head01:
          ansible_host: 192.168.56.10
          ansible_connection: local
    login:
      hosts:
        login01:
          ansible_host: 192.168.56.20
    compute:
      hosts:
        compute01:
          ansible_host: 192.168.56.30
        compute02:
          ansible_host: 192.168.56.31
    storage:
      hosts:
        storage01:
          ansible_host: 192.168.56.50