all:
  vars:
    ansible_user: root 
    ansible_become: true

  children:
    head:
      hosts:
        head01:
          ansible_host: localhost
          ansible_connection: local
    login:
      hosts:
        login01:
          ansible_host: 10.0.0.3
    compute:
      hosts:
        compute01:
          ansible_host: 10.0.0.5
        compute02:
          ansible_host: 10.0.0.6
    storage:
      hosts:
        storage01:
          ansible_host: 10.0.0.7