---
# Slurm Worker Handlers

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted
    daemon_reload: yes

- name: reload slurmd
  systemd:
    name: slurmd
    state: reloaded
